# Generated by Django 6.0.6 on 2026-06-26 01:22

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for this menu', max_length=100)),
                ('slug', models.SlugField(help_text='Unique slug for this menu', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Navigation Menu',
                'verbose_name_plural': 'Navigation Menus',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(blank=True, help_text='Title to display for this menu item', max_length=50)),
                ('link_url', models.CharField(blank=True, help_text='URL for this menu item', max_length=500)),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Open this link in a new tab')),
                ('sort_order', models.PositiveIntegerField(default=0, editable=False)),
                ('link_page', models.ForeignKey(blank=True, help_text='Page for this menu item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
                ('menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='navigation.menu')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent menu item for nested menus', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['sort_order'],
            },
        ),
    ]
