# Generated by Django 6.0.6 on 2026-06-26 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the Cta.', max_length=256)),
                ('description', models.TextField(help_text='A brief description for the Cta.')),
                ('button_text', models.CharField(help_text='Text for the button.', max_length=256)),
                ('button_url', models.URLField(help_text='URL for the button.')),
                ('style', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('cta', 'CTA'), ('button', 'Button'), ('link', 'Link')], default='primary', help_text='Style variant for the Cta', max_length=50)),
                ('header_script', models.TextField(blank=True, help_text='Additional script to inject in the header when this CTA is used.', null=True)),
                ('footer_script', models.TextField(blank=True, help_text='Additional script to inject in the footer when this CTA is used.', null=True)),
            ],
            options={
                'verbose_name': 'Reusable CTA',
                'verbose_name_plural': 'Reusable CTAs',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The question.', max_length=255)),
                ('answer', models.TextField(help_text='The answer.')),
                ('category', models.CharField(choices=[('general', 'General'), ('pricing', 'Pricing'), ('technical', 'Technical')], default='general', help_text='Category for the FAQ', max_length=20)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the team member.', max_length=255)),
                ('role', models.CharField(help_text='The role of the team member.', max_length=255)),
                ('photo', models.ForeignKey(help_text='A photo of the team member.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(help_text='The testimonial quote.')),
                ('author', models.CharField(help_text='The author of the testimonial.', max_length=255)),
                ('image', models.ForeignKey(blank=True, help_text='An optional image of the author.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
