# Generated by Django 6.0.6 on 2026-06-26 01:22

import apps.snippets.models
import django.core.serializers.json
import django.db.models.deletion
import modelcluster.fields
import uuid
import wagtail.fields
import wagtail_flexible_forms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('custom_structured_data', models.TextField(blank=True, help_text='Additional structured data for this page in JSON-LD format.', null=True)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 6), ('quote', 8), ('embed', 9), ('button', 13), ('card', 19), ('cta', 20), ('testimonial', 22), ('team_member', 24), ('faq', 26), ('cta_snippet', 28), ('two_column', 30), ('three_column', 31), ('hero', 39), ('slider', 40), ('marquee', 41), ('table', 47)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('apps.blocks.models.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {'required': True}), 8: ('wagtail.blocks.StructBlock', [[('quote', 7), ('author', 5), ('author_title', 5)]], {}), 9: ('apps.blocks.models.EmbedBlock', (), {}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 11: ('wagtail.blocks.URLBlock', (), {'required': True}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')]}), 13: ('wagtail.blocks.StructBlock', [[('button_text', 10), ('link', 11), ('style', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 15: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 16: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 17: ('wagtail.blocks.URLBlock', (), {'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('title', 14), ('text', 15), ('image', 16), ('link', 17), ('link_text', 18)]], {}), 20: ('wagtail.blocks.StructBlock', [[('title', 14), ('text', 15), ('button_text', 10), ('button_link', 11), ('button_style', 12)]], {}), 21: ('wagtail.snippets.blocks.SnippetChooserBlock', (apps.snippets.models.Testimonial,), {}), 22: ('wagtail.blocks.StructBlock', [[('testimonial', 21)]], {}), 23: ('wagtail.snippets.blocks.SnippetChooserBlock', (apps.snippets.models.TeamMember,), {}), 24: ('wagtail.blocks.StructBlock', [[('team_member', 23)]], {}), 25: ('wagtail.snippets.blocks.SnippetChooserBlock', (apps.snippets.models.Faq,), {}), 26: ('wagtail.blocks.StructBlock', [[('faq', 25)]], {}), 27: ('wagtail.snippets.blocks.SnippetChooserBlock', (apps.snippets.models.Cta,), {}), 28: ('wagtail.blocks.StructBlock', [[('cta', 27)]], {}), 29: ('wagtail.blocks.StreamBlock', [[('heading', 2), ('paragraph', 3), ('image', 6), ('quote', 8), ('embed', 9), ('button', 13), ('card', 19), ('cta', 20), ('testimonial', 22), ('team_member', 24), ('faq', 26), ('cta_snippet', 28)]], {'required': False}), 30: ('wagtail.blocks.StructBlock', [[('left_column', 29), ('right_column', 29)]], {}), 31: ('wagtail.blocks.StructBlock', [[('left_column', 29), ('middle_column', 29), ('right_column', 29)]], {}), 32: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 33: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text-white', 'White'), ('text-black', 'Black'), ('text-gray-800', 'Dark Gray')]}), 34: ('wagtail.blocks.StructBlock', [[('title', 14), ('subtitle', 32), ('background_image', 16), ('text_color', 33), ('cta_button_text', 18), ('cta_button_link', 17), ('cta_button_style', 12)]], {}), 35: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 36: ('wagtail.blocks.StructBlock', [[('title', 14), ('subtitle', 32), ('image', 4), ('image_side', 35), ('cta_button_text', 18), ('cta_button_link', 17), ('cta_button_style', 12)]], {}), 37: ('apps.blocks.models.EmbedBlock', (), {'required': True}), 38: ('wagtail.blocks.StructBlock', [[('title', 14), ('subtitle', 32), ('video', 37), ('text_color', 33), ('cta_button_text', 18), ('cta_button_link', 17), ('cta_button_style', 12)]], {}), 39: ('wagtail.blocks.StreamBlock', [[('simple_hero', 34), ('side_by_side_hero', 36), ('video_hero', 38)]], {}), 40: ('wagtail.blocks.StructBlock', [[('slides', 29)]], {}), 41: ('wagtail.blocks.StructBlock', [[('items', 29)]], {}), 42: ('wagtail.blocks.CharBlock', (), {'label': 'Column'}), 43: ('wagtail.blocks.ListBlock', (42,), {'label': 'Header row', 'required': False}), 44: ('wagtail.blocks.CharBlock', (), {'label': 'Cell'}), 45: ('wagtail.blocks.ListBlock', (44,), {}), 46: ('wagtail.blocks.ListBlock', (45,), {'label': 'Table rows'}), 47: ('wagtail.blocks.StructBlock', [[('table_header', 43), ('table_body', 46)]], {})})),
                ('thank_you_text', models.TextField(blank=True, help_text='Text to display after form submission')),
                ('form_fields', wagtail.fields.StreamField([('char', 5), ('text', 7), ('number', 8), ('checkbox', 10), ('radios', 13), ('dropdown', 13), ('checkboxes', 16), ('date', 18), ('time', 20), ('datetime', 22), ('image', 23), ('file', 23), ('text_markup', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Label'}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Help text', 'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'label': 'Required', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('email', 'Email'), ('url', 'URL')], 'label': 'Format', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Default value', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('help_text', 1), ('required', 2), ('format', 3), ('default_value', 4)]], {'group': 'Fields'}), 6: ('wagtail.blocks.TextBlock', (), {'label': 'Default value', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('help_text', 1), ('required', 2), ('default_value', 6)]], {'group': 'Fields'}), 8: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('help_text', 1), ('required', 2), ('default_value', 4)]], {'group': 'Fields'}), 9: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('help_text', 1), ('default_value', 9)]], {'group': 'Fields'}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Choice'}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('help_text', 1), ('required', 2), ('choices', 12)]], {'group': 'Fields'}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Checkbox'}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('help_text', 1), ('required', 2), ('checkboxes', 15)]], {'group': 'Fields'}), 17: ('wagtail.blocks.DateBlock', (), {'required': False}), 18: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('help_text', 1), ('required', 2), ('default_value', 17)]], {'group': 'Fields'}), 19: ('wagtail.blocks.TimeBlock', (), {'required': False}), 20: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('help_text', 1), ('required', 2), ('default_value', 19)]], {'group': 'Fields'}), 21: ('wagtail.blocks.DateTimeBlock', (), {'required': False}), 22: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('help_text', 1), ('required', 2), ('default_value', 21)]], {'group': 'Fields'}), 23: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('help_text', 1), ('required', 2)]], {'group': 'Fields'}), 24: ('wagtail.blocks.RichTextBlock', (), {'group': 'Other'})})),
                ('to_address', models.CharField(blank=True, help_text='Optional - email address to send submissions to', max_length=255)),
                ('from_address', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_flexible_forms.models.StreamFormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='SubmissionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('created', 'Created'), ('changed', 'Changed'), ('deleted', 'Deleted')], max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission_id', models.TextField()),
                ('data', models.TextField()),
                ('summary', models.TextField()),
                ('submission_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='submit time')),
                ('session_key', models.CharField(default=None, max_length=40, null=True)),
                ('last_modification', models.DateTimeField(auto_now=True, verbose_name='last modification')),
                ('status', models.CharField(choices=[('incomplete', 'Not submitted'), ('complete', 'Complete'), ('reviewed', 'Under consideration'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='incomplete', max_length=10)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='forms.formpage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'form submission',
                'verbose_name_plural': 'form submissions',
                'abstract': False,
                'unique_together': {('page', 'session_key'), ('page', 'user')},
            },
        ),
    ]
