# Generated by Django 6.0.6 on 2026-06-26 01:22

import apps.snippets.models
import django.db.models.deletion
import modelcluster.fields
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('custom_structured_data', models.TextField(blank=True, help_text='Additional structured data for this page in JSON-LD format.', null=True)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 6), ('quote', 8), ('embed', 9), ('button', 13), ('card', 19), ('cta', 20), ('testimonial', 22), ('team_member', 24), ('faq', 26), ('cta_snippet', 28), ('two_column', 30), ('three_column', 31), ('hero', 39), ('slider', 40), ('marquee', 41), ('table', 47)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('apps.blocks.models.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {'required': True}), 8: ('wagtail.blocks.StructBlock', [[('quote', 7), ('author', 5), ('author_title', 5)]], {}), 9: ('apps.blocks.models.EmbedBlock', (), {}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 11: ('wagtail.blocks.URLBlock', (), {'required': True}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')]}), 13: ('wagtail.blocks.StructBlock', [[('button_text', 10), ('link', 11), ('style', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 15: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 16: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 17: ('wagtail.blocks.URLBlock', (), {'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('title', 14), ('text', 15), ('image', 16), ('link', 17), ('link_text', 18)]], {}), 20: ('wagtail.blocks.StructBlock', [[('title', 14), ('text', 15), ('button_text', 10), ('button_link', 11), ('button_style', 12)]], {}), 21: ('wagtail.snippets.blocks.SnippetChooserBlock', (apps.snippets.models.Testimonial,), {}), 22: ('wagtail.blocks.StructBlock', [[('testimonial', 21)]], {}), 23: ('wagtail.snippets.blocks.SnippetChooserBlock', (apps.snippets.models.TeamMember,), {}), 24: ('wagtail.blocks.StructBlock', [[('team_member', 23)]], {}), 25: ('wagtail.snippets.blocks.SnippetChooserBlock', (apps.snippets.models.Faq,), {}), 26: ('wagtail.blocks.StructBlock', [[('faq', 25)]], {}), 27: ('wagtail.snippets.blocks.SnippetChooserBlock', (apps.snippets.models.Cta,), {}), 28: ('wagtail.blocks.StructBlock', [[('cta', 27)]], {}), 29: ('wagtail.blocks.StreamBlock', [[('heading', 2), ('paragraph', 3), ('image', 6), ('quote', 8), ('embed', 9), ('button', 13), ('card', 19), ('cta', 20), ('testimonial', 22), ('team_member', 24), ('faq', 26), ('cta_snippet', 28)]], {'required': False}), 30: ('wagtail.blocks.StructBlock', [[('left_column', 29), ('right_column', 29)]], {}), 31: ('wagtail.blocks.StructBlock', [[('left_column', 29), ('middle_column', 29), ('right_column', 29)]], {}), 32: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 33: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text-white', 'White'), ('text-black', 'Black'), ('text-gray-800', 'Dark Gray')]}), 34: ('wagtail.blocks.StructBlock', [[('title', 14), ('subtitle', 32), ('background_image', 16), ('text_color', 33), ('cta_button_text', 18), ('cta_button_link', 17), ('cta_button_style', 12)]], {}), 35: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 36: ('wagtail.blocks.StructBlock', [[('title', 14), ('subtitle', 32), ('image', 4), ('image_side', 35), ('cta_button_text', 18), ('cta_button_link', 17), ('cta_button_style', 12)]], {}), 37: ('apps.blocks.models.EmbedBlock', (), {'required': True}), 38: ('wagtail.blocks.StructBlock', [[('title', 14), ('subtitle', 32), ('video', 37), ('text_color', 33), ('cta_button_text', 18), ('cta_button_link', 17), ('cta_button_style', 12)]], {}), 39: ('wagtail.blocks.StreamBlock', [[('simple_hero', 34), ('side_by_side_hero', 36), ('video_hero', 38)]], {}), 40: ('wagtail.blocks.StructBlock', [[('slides', 29)]], {}), 41: ('wagtail.blocks.StructBlock', [[('items', 29)]], {}), 42: ('wagtail.blocks.CharBlock', (), {'label': 'Column'}), 43: ('wagtail.blocks.ListBlock', (42,), {'label': 'Header row', 'required': False}), 44: ('wagtail.blocks.CharBlock', (), {'label': 'Cell'}), 45: ('wagtail.blocks.ListBlock', (44,), {}), 46: ('wagtail.blocks.ListBlock', (45,), {'label': 'Table rows'}), 47: ('wagtail.blocks.StructBlock', [[('table_header', 43), ('table_body', 46)]], {})})),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
            ],
            options={
                'verbose_name': 'Flex Page',
                'verbose_name_plural': 'Flex Pages',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ResourceShowcaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(default='Untitled', help_text='Title for this item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description for this item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioShowcaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(default='Untitled', help_text='Title for this item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description for this item')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', models.ForeignKey(blank=True, help_text='Optional page to link to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioShowcaseItemLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('target', models.CharField(choices=[('_self', 'Same Window'), ('_blank', 'New Window')], default='_self', max_length=10)),
                ('item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pages.portfolioshowcaseitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioShowcasePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('custom_structured_data', models.TextField(blank=True, help_text='Additional structured data for this page in JSON-LD format.', null=True)),
                ('introduction', models.TextField(blank=True, help_text='Optional introduction text for the showcase page')),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
            ],
            options={
                'verbose_name': 'Portfolio Showcase Page',
                'verbose_name_plural': 'Portfolio Showcase Pages',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='PortfolioShowcaseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('heading', models.CharField(help_text='Heading for this section', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description for this section')),
                ('showcase_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_sections', to='pages.portfolioshowcasepage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='portfolioshowcaseitem',
            name='section',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.portfolioshowcasesection'),
        ),
        migrations.CreateModel(
            name='ProjectShowcaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(default='Untitled', help_text='Title for this item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description for this item')),
                ('page', models.ForeignKey(blank=True, help_text='Optional page to link to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectShowcaseItemLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('target', models.CharField(choices=[('_self', 'Same Window'), ('_blank', 'New Window')], default='_self', max_length=10)),
                ('item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pages.projectshowcaseitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectShowcasePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('custom_structured_data', models.TextField(blank=True, help_text='Additional structured data for this page in JSON-LD format.', null=True)),
                ('introduction', models.TextField(blank=True, help_text='Optional introduction text for the showcase page')),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
            ],
            options={
                'verbose_name': 'Project Showcase Page',
                'verbose_name_plural': 'Project Showcase Pages',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ProjectShowcaseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('heading', models.CharField(help_text='Heading for this section', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description for this section')),
                ('showcase_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_sections', to='pages.projectshowcasepage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='projectshowcaseitem',
            name='section',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.projectshowcasesection'),
        ),
        migrations.CreateModel(
            name='ResourceShowcaseItemLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('target', models.CharField(choices=[('_self', 'Same Window'), ('_blank', 'New Window')], default='_self', max_length=10)),
                ('item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pages.resourceshowcaseitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceShowcasePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('custom_structured_data', models.TextField(blank=True, help_text='Additional structured data for this page in JSON-LD format.', null=True)),
                ('introduction', models.TextField(blank=True, help_text='Optional introduction text for the showcase page')),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
            ],
            options={
                'verbose_name': 'Resource Showcase Page',
                'verbose_name_plural': 'Resource Showcase Pages',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ResourceShowcaseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('heading', models.CharField(help_text='Heading for this section', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description for this section')),
                ('showcase_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_sections', to='pages.resourceshowcasepage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resourceshowcaseitem',
            name='section',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.resourceshowcasesection'),
        ),
        migrations.CreateModel(
            name='ServiceShowcaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(default='Untitled', help_text='Title for this item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description for this item')),
                ('page', models.ForeignKey(blank=True, help_text='Optional page to link to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceShowcaseItemLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('target', models.CharField(choices=[('_self', 'Same Window'), ('_blank', 'New Window')], default='_self', max_length=10)),
                ('item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pages.serviceshowcaseitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceShowcasePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('custom_structured_data', models.TextField(blank=True, help_text='Additional structured data for this page in JSON-LD format.', null=True)),
                ('introduction', models.TextField(blank=True, help_text='Optional introduction text for the showcase page')),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
            ],
            options={
                'verbose_name': 'Service Showcase Page',
                'verbose_name_plural': 'Service Showcase Pages',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ServiceShowcaseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('heading', models.CharField(help_text='Heading for this section', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description for this section')),
                ('showcase_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_sections', to='pages.serviceshowcasepage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='serviceshowcaseitem',
            name='section',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.serviceshowcasesection'),
        ),
        migrations.CreateModel(
            name='PortfolioItemPage',
            fields=[
                ('flexpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.flexpage')),
                ('url_type_preference', models.CharField(choices=[('seo', 'SEO-friendly Slug'), ('uuid', 'UUID-based')], default='seo', help_text='Choose whether to display SEO-friendly URLs or UUID-based URLs', max_length=10)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.tag')),
            ],
            options={
                'verbose_name': 'Portfolio Item Page',
                'verbose_name_plural': 'Portfolio Item Pages',
            },
            bases=('pages.flexpage',),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('flexpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.flexpage')),
                ('url_type_preference', models.CharField(choices=[('seo', 'SEO-friendly Slug'), ('uuid', 'UUID-based')], default='seo', help_text='Choose whether to display SEO-friendly URLs or UUID-based URLs', max_length=10)),
                ('has_page', models.BooleanField(default=False, help_text='Check this box if this project has its own page')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.tag')),
            ],
            options={
                'verbose_name': 'Project Page',
                'verbose_name_plural': 'Project Pages',
            },
            bases=('pages.flexpage',),
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('flexpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.flexpage')),
                ('url_type_preference', models.CharField(choices=[('seo', 'SEO-friendly Slug'), ('uuid', 'UUID-based')], default='seo', help_text='Choose whether to display SEO-friendly URLs or UUID-based URLs', max_length=10)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.tag')),
            ],
            options={
                'verbose_name': 'Service Page',
                'verbose_name_plural': 'Service Pages',
            },
            bases=('pages.flexpage',),
        ),
    ]
